Remove insmod statements from GRUB config
Ubuntu's signed GRUB has limited embedded modules and looks for
additional modules in /EFI/ubuntu/arm64-efi/ which doesn't exist
in our setup. This caused errors like:
  error: file '/EFI/ubuntu/arm64-efi/ntfs.mod' not found

The signed GRUB already has core modules embedded (part_gpt, fat,
ntfs, linux, search, chain, etc.) so we don't need explicit insmod
statements. Removed all insmod calls to use only embedded modules.